#!/usr/bin/env python3
"""Generate docs/economics/token-tracker.md from tokencost/cost.csv."""

import csv
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


BRANCH_RE = re.compile(r"sf_businesscapability-(\d+)$")
PREAMBLE = (
    "# Token Tracker\n\n"
    "Generated by `scripts/generate_token_tracker.py`. "
    "Notes column is human-editable — avoid `|` characters.\n"
)
TABLE_HEADER = (
    "\n| Branch | Issue | Summary | Total Cost (USD) | Notes |\n"
    "|--------|-------|---------|------------------|-------|\n"
)


def branch_to_issue_number(branch: str) -> Optional[int]:
    m = BRANCH_RE.search(branch)
    return int(m.group(1)) if m else None


def aggregate(rows: list[dict]) -> dict:
    """Return {branch: {cost_sum, n_sessions, n_errors}}."""
    result = {}
    for row in rows:
        branch = row.get("git_branch", "").strip() or "(no branch)"
        cost_raw = row.get("total_cost_usd", "").strip()
        is_error = cost_raw.upper() == "ERROR"
        entry = result.setdefault(branch, {"cost_sum": 0.0, "n_sessions": 0, "n_errors": 0})
        entry["n_sessions"] += 1
        if is_error:
            entry["n_errors"] += 1
        else:
            try:
                entry["cost_sum"] += float(cost_raw)
            except ValueError:
                entry["n_errors"] += 1
    return result


def format_cost(cost_sum: float, n_errors: int, n_sessions: int) -> str:
    if n_errors == 0:
        return f"${cost_sum:.2f}"
    if n_errors == n_sessions:
        return "$0.00 (all sessions errored)"
    return f"${cost_sum:.2f} (some sessions errored)"


def parse_repo_url(remote_url: str) -> str:
    remote_url = remote_url.strip()
    # SSH: git@github.com:foo/bar.git
    m = re.match(r"git@([^:]+):(.+?)(?:\.git)?$", remote_url)
    if m:
        return f"https://{m.group(1)}/{m.group(2)}"
    # HTTPS: https://github.com/foo/bar.git
    return re.sub(r"\.git$", "", remote_url)


def get_repo_url() -> str:
    try:
        out = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return parse_repo_url(out)
    except Exception:
        return "https://github.com/unknown/unknown"


def parse_existing_md(md_text: str) -> dict:
    """Return {branch: {issue, summary, notes}} from existing md table.

    Skips Total row, warns on rows with extra pipes.
    """
    result = {}
    in_table = False
    header_seen = False
    for line in md_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and not in_table:
            in_table = True
        if not in_table or not stripped.startswith("|"):
            continue
        # Skip separator row
        if re.match(r"^\|[-| ]+\|$", stripped):
            header_seen = True
            continue
        if not header_seen:
            continue
        parts = stripped.split("|")
        # parts[0] and parts[-1] are empty (outside pipes)
        cols = [p.strip() for p in parts[1:-1]]
        if len(cols) < 5:
            print(
                f"warning: unexpected column count ({len(cols)}) in row: {line!r}",
                file=sys.stderr,
            )
            continue
        branch, issue, summary, _cost = cols[0], cols[1], cols[2], cols[3]
        # Rejoin extra pipe-split fragments in Notes (user accidentally typed |)
        notes = "|".join(cols[4:])
        if len(cols) > 5:
            print(
                f"warning: extra pipes in Notes for branch {branch!r} — joined as-is",
                file=sys.stderr,
            )
        if branch == "**Total**":
            continue
        result[branch] = {"issue": issue, "summary": summary, "notes": notes}
    return result


def emit_md(branch_data: dict, repo_url: str) -> str:
    """Build full markdown text.

    branch_data: {branch: {cost_sum, n_errors, n_sessions, issue, summary, notes}}
    """
    total_cost = sum(v["cost_sum"] for v in branch_data.values())
    total_errors = sum(v["n_errors"] for v in branch_data.values())
    total_sessions = sum(v["n_sessions"] for v in branch_data.values())
    total_cell = format_cost(total_cost, total_errors, total_sessions)

    rows_sorted = sorted(branch_data.items(), key=lambda kv: kv[1]["cost_sum"], reverse=True)

    lines = [PREAMBLE, TABLE_HEADER]
    lines.append(f"| **Total** | — | — | {total_cell} | — |\n")
    for branch, v in rows_sorted:
        issue_val = v.get("issue", "—")
        summary_val = v.get("summary", "—")
        notes_val = v.get("notes", "—")
        cost_cell = format_cost(v["cost_sum"], v["n_errors"], v["n_sessions"])
        lines.append(f"| {branch} | {issue_val} | {summary_val} | {cost_cell} | {notes_val} |\n")

    return "".join(lines)


def fetch_title_gh(issue_num: int, repo_url: str) -> Optional[str]:
    """Call gh to fetch issue title. Returns None on failure."""
    # Derive OWNER/REPO from repo_url
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", repo_url)
    if not m:
        return None
    repo_path = m.group(1)
    try:
        title = subprocess.check_output(
            ["gh", "issue", "view", str(issue_num), "--repo", repo_path,
             "--json", "title", "-q", ".title"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return title or None
    except Exception:
        return None


def run(
    csv_path: Path,
    md_path: Path,
    fetch_title=None,
    get_remote_url=None,
):
    if fetch_title is None:
        fetch_title = fetch_title_gh
    if get_remote_url is None:
        get_remote_url = get_repo_url

    if not csv_path.exists():
        print(f"error: tokencost/cost.csv not found at {csv_path.resolve()}", file=sys.stderr)
        sys.exit(1)

    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    agg = aggregate(rows)

    # Parse existing md for cached issue/summary/notes
    existing: dict = {}
    if md_path.exists():
        existing = parse_existing_md(md_path.read_text())

    repo_url = get_remote_url()

    branch_data = {}
    for branch, stats in agg.items():
        entry = {**stats}
        cached = existing.get(branch, {})
        issue_cached = cached.get("issue", "—")
        summary_cached = cached.get("summary", "—")
        notes_cached = cached.get("notes", "—")

        issue_num = branch_to_issue_number(branch)

        # Determine if we need to fetch
        needs_fetch = (
            issue_num is not None
            and (summary_cached in ("—", "(title unavailable)") or issue_cached == "—")
        )

        if needs_fetch:
            title = fetch_title(issue_num, repo_url)
            if title:
                issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
                summary_val = title
            else:
                issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
                summary_val = "(title unavailable)"
                print(
                    f"warning: could not fetch title for issue #{issue_num} — "
                    "will retry on next run",
                    file=sys.stderr,
                )
        elif issue_num is not None and issue_cached != "—":
            # Use cache
            issue_val = issue_cached
            summary_val = summary_cached
        elif issue_num is not None:
            issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
            summary_val = summary_cached
        else:
            issue_val = "—"
            summary_val = "—"

        entry["issue"] = issue_val
        entry["summary"] = summary_val
        entry["notes"] = notes_cached
        branch_data[branch] = entry

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(emit_md(branch_data, repo_url))
    print(f"wrote {md_path}")


def main():
    try:
        repo_root = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        )
    except subprocess.CalledProcessError:
        print("error: not inside a git repository", file=sys.stderr)
        sys.exit(1)
    csv_path = repo_root / "tokencost" / "cost.csv"
    md_path = repo_root / "docs" / "economics" / "token-tracker.md"
    run(csv_path, md_path)


if __name__ == "__main__":
    main()
