"""Unit tests for generate_token_tracker.py — stdlib only, no I/O."""

import io
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tokencost.generate_token_tracker import (  # noqa: E402
    aggregate,
    branch_to_issue_number,
    emit_md,
    format_cost,
    parse_existing_md,
    parse_repo_url,
    run,
)


REPO_URL = "https://github.com/owner/repo"


class TestBranchToIssueNumber(unittest.TestCase):
    def test_matches(self):
        self.assertEqual(branch_to_issue_number("sf_businesscapability-42"), 42)

    def test_feature_prefix(self):
        self.assertEqual(branch_to_issue_number("feature/sf_businesscapability-22"), 22)

    def test_no_match_main(self):
        self.assertIsNone(branch_to_issue_number("main"))

    def test_no_match_random(self):
        self.assertIsNone(branch_to_issue_number("random-branch"))


class TestAggregate(unittest.TestCase):
    def _row(self, branch, cost):
        return {"git_branch": branch, "total_cost_usd": cost}

    def test_sum_clean(self):
        rows = [self._row("main", "1.00"), self._row("main", "2.50")]
        result = aggregate(rows)
        self.assertAlmostEqual(result["main"]["cost_sum"], 3.50)
        self.assertEqual(result["main"]["n_errors"], 0)

    def test_excludes_error(self):
        rows = [self._row("main", "5.00"), self._row("main", "ERROR")]
        result = aggregate(rows)
        self.assertAlmostEqual(result["main"]["cost_sum"], 5.00)
        self.assertEqual(result["main"]["n_errors"], 1)
        self.assertEqual(result["main"]["n_sessions"], 2)

    def test_all_error(self):
        rows = [self._row("main", "ERROR"), self._row("main", "ERROR")]
        result = aggregate(rows)
        self.assertAlmostEqual(result["main"]["cost_sum"], 0.0)
        self.assertEqual(result["main"]["n_errors"], 2)
        self.assertEqual(result["main"]["n_sessions"], 2)

    def test_empty_branch(self):
        rows = [{"git_branch": "", "total_cost_usd": "1.00"}]
        result = aggregate(rows)
        self.assertIn("(no branch)", result)


class TestFormatCost(unittest.TestCase):
    def test_clean(self):
        self.assertEqual(format_cost(5.23, 0, 2), "$5.23")

    def test_mixed_error(self):
        self.assertEqual(format_cost(5.23, 1, 2), "$5.23 (some sessions errored)")

    def test_all_error(self):
        self.assertEqual(format_cost(0.0, 2, 2), "$0.00 (all sessions errored)")


class TestParseExistingMd(unittest.TestCase):
    SAMPLE_MD = """\
# Token Tracker

Generated by script.

| Branch | Issue | Summary | Total Cost (USD) | Notes |
|--------|-------|---------|------------------|-------|
| **Total** | — | — | $10.00 | — |
| main | — | — | $8.00 | my note |
| sf_businesscapability-32 | [#32](https://github.com/x/y/issues/32) | Remove ctx menu | $2.00 | — |
"""

    def test_roundtrip(self):
        result = parse_existing_md(self.SAMPLE_MD)
        self.assertIn("main", result)
        self.assertEqual(result["main"]["notes"], "my note")
        self.assertEqual(result["sf_businesscapability-32"]["summary"], "Remove ctx menu")

    def test_skips_total_row(self):
        result = parse_existing_md(self.SAMPLE_MD)
        self.assertNotIn("**Total**", result)

    def test_pipe_in_notes_warns_and_preserves(self):
        bad_md = """\
| Branch | Issue | Summary | Total Cost (USD) | Notes |
|--------|-------|---------|------------------|-------|
| main | — | — | $1.00 | note | extra |
"""
        stderr_capture = io.StringIO()
        old_stderr = sys.stderr
        sys.stderr = stderr_capture
        try:
            result = parse_existing_md(bad_md)
        finally:
            sys.stderr = old_stderr
        self.assertIn("warning", stderr_capture.getvalue())
        # Notes should be joined, not discarded
        self.assertIn("main", result)
        self.assertEqual(result["main"]["notes"], "note|extra")


class TestEmitMd(unittest.TestCase):
    def _make_data(self):
        return {
            "main": {"cost_sum": 8.0, "n_errors": 0, "n_sessions": 2,
                     "issue": "—", "summary": "—", "notes": "—"},
            "sf_businesscapability-32": {"cost_sum": 2.0, "n_errors": 0, "n_sessions": 1,
                                          "issue": "[#32](url)", "summary": "Remove ctx menu", "notes": "—"},
        }

    def test_sorts_desc_total_at_top(self):
        out = emit_md(self._make_data(), REPO_URL)
        lines = [l for l in out.splitlines() if l.startswith("|")]
        # header, separator, total, main (8.0), sf-32 (2.0)
        self.assertIn("**Total**", lines[2])
        self.assertIn("main", lines[3])
        self.assertIn("sf_businesscapability-32", lines[4])

    def test_em_dash_for_missing(self):
        data = {
            "main": {"cost_sum": 1.0, "n_errors": 0, "n_sessions": 1,
                     "issue": "—", "summary": "—", "notes": "—"},
        }
        out = emit_md(data, REPO_URL)
        # main row should have em dashes for issue and summary
        row_line = [l for l in out.splitlines() if "main" in l and "**Total**" not in l][0]
        self.assertIn("—", row_line)


class TestParseRepoUrl(unittest.TestCase):
    def test_https(self):
        self.assertEqual(
            parse_repo_url("https://github.com/foo/bar.git"),
            "https://github.com/foo/bar",
        )

    def test_ssh(self):
        self.assertEqual(
            parse_repo_url("git@github.com:foo/bar.git"),
            "https://github.com/foo/bar",
        )


class TestFetchTitleInjection(unittest.TestCase):
    def test_fake_fetch_title(self):
        titles = {42: "My feature title"}

        def fake_fetch(issue_num, repo_url):
            return titles.get(issue_num)

        with tempfile.TemporaryDirectory() as tmpdir:
            # Create minimal cost.csv
            csv_path = Path(tmpdir) / "cost.csv"
            csv_path.write_text(
                "session_id,started_at,ended_at,end_reason,total_cost_usd,"
                "input_tokens,output_tokens,cache_creation_tokens,cache_read_tokens,"
                "total_tokens,models,git_branch\n"
                "abc,2026-01-01,2026-01-01,end,1.50,0,0,0,0,0,model,sf_businesscapability-42\n"
            )
            md_path = Path(tmpdir) / "docs" / "economics" / "token-tracker.md"

            run(csv_path, md_path, fetch_title=fake_fetch, get_remote_url=lambda: REPO_URL)

            content = md_path.read_text()
            self.assertIn("My feature title", content)
            self.assertIn("#42", content)


if __name__ == "__main__":
    unittest.main()
